<nav class="navbar navbar-dark navbar-expand-sm mb-5 fixed-top">
	<div class="container">		

		<button class="navbar-toggler" type="button"
			data-toggle="collapse" data-target="#myTogglerNav" aria-controls="myTogglerNav" 
			aria-expanded="false" 
			aria-label="Toggle Navigation">
				<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="myTogglerNav">
			<div class="navbar-nav ml-auto">
				<a class="nav-item nav-link" href="#">Blog</a>
				<a class="nav-item nav-link" href="#experience">About Me</a>	
				<a class="nav-item nav-link" href="#">Contact</a>					
			</div>
		</div>
	</div>
</nav>